### ISSUE TITLE
undefined method `result' for nil:NilClass start coming when upgraded to 0.3.6

### ISSUE THREAD

**Issue by saubi1993** [holyketzer/activeadmin-ajax_filter#17]
error is coming here :

f.input :virtual_manufacturer, label: "Manufacturer", as: :ajax_select, data: {
          url: autocomplete_path,
          search_fields: [:manufacturer],
      }

**Comment by holyketzer** [comment]
Try version 0.3.7
